openapi: 3.0.3
info:
  title: MQTT Device Control API
  version: 1.0.0
  description: API to send MQTT messages to control devices via Mosquitto broker on Raspberry Pi.

servers:
  - url: http://pi5.local:5000
    description: Local Flask server

paths:
  /control-device:
    post:
      summary: Publish a message to an MQTT topic
      description: Sends a message to the specified MQTT topic and saves state persistently.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - topic
                - value
              properties:
                topic:
                  type: string
                  description: MQTT topic to publish to (e.g., pico/led/brightness)
                  example: pico/led/brightness
                value:
                  description: Value/message to publish to the topic (string or number)
                  oneOf:
                    - type: string
                      example: "50"
                    - type: integer
                      example: 75
            example:
              topic: pico/relay
              value: "on"
      responses:
        '200':
          description: Message published successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          description: Missing or invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: Missing 'topic' or 'value'
        '500':
          description: MQTT publishing failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
        '503':
          description: Device is offline
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: Device `device-name` is offline.
  /get-state:
    get:
      summary: Get current device state
      description: Returns the current stored MQTT state from status.json
      responses:
        '200':
          description: Current device state returned successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  oneOf:
                    - type: string
                    - type: integer
                    - type: boolean
                example:
                  pico/led: "on"
                  pico/led/brightness: 75
        '500':
          description: Server error retrieving status
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false

  /weather:
    get:
      summary: Get current weather data
      description: Returns current weather data for a fixed location using OpenWeatherMap API.
      responses:
        '200':
          description: Weather data returned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  weather:
                    type: array
                    items:
                      type: object
                  main:
                    type: object
                  wind:
                    type: object
                  name:
                    type: string
                example:
                  weather:
                    - description: "clear sky"
                      icon: "01d"
                  main:
                    temp: 293.55
                    humidity: 56
                  wind:
                    speed: 3.6
                  name: "London"
        '500':
          description: Error retrieving weather data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
